GET http://localhost:9090/api/v1/user
###

POST http://localhost:9090/api/v1/user
Content-Type: application/json

{
    "ID": "62b56b9957edc5d8e234545d",
    "Username": "Ricardo Gomez Bolaños",
    "CreatedAt": "2022-06-30T08:51:00.603Z"
}
###

DELETE http://localhost:9090/api/v1/auth/user/62bd6416f8242b9a38e31234
###
